# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQemZh1DfMbWzSeIVD5CGYdcZnqitlRh
"""

from math import dist;

posicaoRato = [ int(input("Digite a posição X do rato: ")) , int(input("Digite a posição y do rato: "))];
posicaoGato = [ int(input("Digite a posição X do gato: ")) , int(input("Digite a posição y do gato: "))];

print("Distância euclidiana: ", dist(posicaoGato, posicaoRato));

if (posicaoGato[0] < posicaoRato[0]):
  distX = posicaoRato[0] - posicaoGato[0];
else:
  distX = posicaoGato[0] - posicaoRato[0];

if (posicaoGato[1] < posicaoRato[1]):
  distY = posicaoRato[1] - posicaoGato[1];
else:
  distY = posicaoGato[1] - posicaoRato[1];

print("Quantidade de casas a andar: ", distX + distY);

if( (distX + distY > 10) ):
  print("O gato não vai andar");
else:
  print("O gato vai andar");

while(posicaoGato[0] > posicaoRato[0]):
  posicaoGato[0]-=1;
  print("Gato[", posicaoGato[0], ",", posicaoGato[1], "] & Rato[", posicaoRato[0], ",", posicaoRato[1], "]");

while(posicaoGato[0] < posicaoRato[0]):
  posicaoGato[0]+=1;
  print("Gato[", posicaoGato[0], ",", posicaoGato[1], "] & Rato[", posicaoRato[0], ",", posicaoRato[1], "]");

while(posicaoGato[1] > posicaoRato[1]):
  posicaoGato[1]-=1;
  print("Gato[", posicaoGato[0], ",", posicaoGato[1], "] & Rato[", posicaoRato[0], ",", posicaoRato[1], "]");

while(posicaoGato[1] < posicaoRato[1]):
  posicaoGato[1]+=1;
  print("Gato[", posicaoGato[0], ",", posicaoGato[1], "] & Rato[", posicaoRato[0], ",", posicaoRato[1], "]");