# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QsmM-yZSrLg5uxy2Q0KrWOCSNcRtx9Na
"""

import math;

a = int( input( "Digite o valor a: " ) );
b = int( input( "Digite o valor b: " ) );
c = int( input( "Digite o valor c: " ) );

delta = b**2 - 4*a*c;

if delta > 0:
  x1 = (-b + math.sqrt(delta))/(2*a);
  x2 = (-b - math.sqrt(delta))/(2*a);
  print("As ráizes são: ", x1, " e ", x2);
else:
  print("Delta negativo");